# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' "inline" allows us to make copies of this function where we need it. This
#' is useful because random_shuffle() needs a dynamic function, not a static
#' vector, in order create a random number stream based on one from R.
NULL

#' rho_value
#'
#' Returns rounded value of rho that can be passed to the number_cars variable.
#' @param x The proportion or number of cars to fill the matrix.
#' @param row The number of rows.
#' @param col The number of columns.
rho_value <- function(x, row, col) {
    .Call(`_carsimr_geisler_rho_value`, x, row, col)
}

#' randomShuffle
#'
#' Shuffles values of a vector randomly.
#' @param a A numeric vector.
randomShuffle <- function(a) {
    .Call(`_carsimr_geisler_randomShuffle`, a)
}

#' generate_and_shuffle
#'
#' Try to shuffle things
#' @param n an integer with the number of things we need to simulate
#' @param n2 an integer with the number of non-zero elements
#' @param p the probability of selecting a one (versus a two)
generate_and_shuffle <- function(n, n2, p) {
    .Call(`_carsimr_geisler_generate_and_shuffle`, n, n2, p)
}

#' C++ version of initialize_grid.
#'
#' @import MASS
#' @param rho The proportion of cars to fill the grid rounded to the nearest
#' whole number
#' @param r The number of rows in the grid
#' @param c The number of columns in the grid
#' @param p The proportion of blue and red cars as determined by the Bernoulli
#' @param seed The seed to be set for reproduceability.
#' distribution
#' @exportClass carsimr
#' @export
initialize_grid_cpp <- function(rho, r, c, p, seed) {
    .Call(`_carsimr_geisler_initialize_grid_cpp`, rho, r, c, p, seed)
}

#' move_red_cpp
#'
#' C++ version of move_red_cars
#'
#' @param m A numeric matrix.
move_red_cpp <- function(m) {
    .Call(`_carsimr_geisler_move_red_cpp`, m)
}

#' move_blue_cpp
#' C++ version of move_blue_cars.
#'
#' @param m A matrix of blue and red cars.
move_blue_cpp <- function(m) {
    .Call(`_carsimr_geisler_move_blue_cpp`, m)
}

#' simulate_grid_cpp_c
#'
#' C++ version of simulate_grid.
#'
#' @param m A numeric matrix of class "carsimr" to be simulated.
#' @param trials Specifies the number of times the cars move on the grid.
#' @export
simulate_grid_cpp_c <- function(m, trials) {
    .Call(`_carsimr_geisler_simulate_grid_cpp_c`, m, trials)
}

#' move_cars_cpp_c
#'
#' C++ version of move_cars
#'
#' @param rho The proportion or number of cars in a grid.
#' @param r The number of rows in the grid.
#' @param c The number of columns in the grid.
#' @param p The proportion of red cars in the grid.
#' @param trials The number of grid movements to be simulated.
#' @export
move_cars_cpp_c <- function(rho, r, c, p, trials) {
    .Call(`_carsimr_geisler_move_cars_cpp_c`, rho, r, c, p, trials)
}

